### PR TITLE
Added a substitution for single quotes in the footnote content.

### PR DESCRIPTION
**Pull request by DavidEBest**
Footnote content that contained a single quote character was being truncated at the quote. This replaces the single quote with an &apos; when the double quote and less than/greater than signs are replaced.

### CODE REVIEW

**Comment by dennisfrank** [comment]
@lemonmade Can you merge this PR? I experienced this issue myself.

**Comment by lemonmade** [comment]
Sorry, never saw this originally. Looks great!

**Comment by dennisfrank** [comment]
Awesome! :)

**Comment by dennisfrank** [comment]
@lemonmade Thanks for the merge. Could you release this under a new version number and update bower.json and package.json too?

**Comment by lemonmade** [comment]
:+1:

**Pull request merged**
